### ISSUE TITLE
关于命名的建议

### ISSUE THREAD

**Issue by iDingDong** [wuye9036/CppTemplateTutorial#18]
建议将所有下划线开头的名字都改一下：

>Each name that begins with an underscore is reserved to the implementation for use as a name in the global namespace.

标准是不建议在全局命名空间出现用户自定义的下划线开头符号的

**Comment by FrankHB** [comment]
套个namespace了事。
虽然是同类项，碍眼程度和实效不及那个并没卵用的`_tmain`。
