### ISSUE TITLE
真的是好文啊

### ISSUE THREAD

**Issue by gggin** [wuye9036/CppTemplateTutorial#20]
继续写啊！！！！

**Comment by imcaffrey** [comment]
Guess this is not a issue= =

**Comment by gggin** [comment]
...I said continue to write! This is a great document!

**Comment by robturtle** [comment]
你知道当别人发现他的github时间线被这种没有信息量的消息占据版面是很无语的吗。你这么一发其他292个watch的人都会收到推送你知道吗。。。 = =

**Comment by gggin** [comment]
sorry for this
