### ISSUE TITLE
is_base_of 的用法错误

### ISSUE THREAD

**Issue by wanttobeno** [wuye9036/CppTemplateTutorial#34]
// TEMPLATE CLASS is_base_of
template<class _Base, class _Der>
	struct is_base_of _IS_BASE_OF(_Base, _Der)
	{	// determine whether _Base is a base of or the same as _Der
	};

Error：
typename std::enable_if<std::is_base_of<T, ICounter>::value>::type* = nullptr)

Right:
typename std::enable_if<std::is_base_of<ICounter, T>::value>::type* = nullptr)

**Comment by vczh** [comment]
fixed
