### ISSUE TITLE
关于 B(A::*)(C&) 语义的理解

### ISSUE THREAD

**Issue by dongmingsun** [wuye9036/CppTemplateTutorial#46]
```cpp
// Tuple的一些用例
tuple<int> a;
tuple<double&, const double&, const double, double*, const double*> b;
tuple<A, int(*)(char, int), B(A::*)(C&), C> c;
tuple<std::string, std::pair<A, B> > d;
tuple<A*, tuple<const A*, const B&, C>, bool, void*> e;
```

这里`int(*)(char, int)`我知道是一个函数指针的写法，但是`B(A::*)(C&)`该作何理解呢？`A::*`是`A`作用域中的星号？如果那样的话不是应该是`operator*`吗？

**Comment by lythesia** [comment]
`B(A::*)(C&)`就是A的成员函数, 其类型是参数为C&, 返回B

**Comment by dongmingsun** [comment]
谢谢，明白了，原来A::只是指定作用域啊

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Yi Lu <notifications@github.com>
发送时间: Monday, September 2, 2019 3:00:31 PM
收件人: wuye9036/CppTemplateTutorial <CppTemplateTutorial@noreply.github.com>
抄送: Dongming <dongming.sun@outlook.com>; Author <author@noreply.github.com>
主题: Re: [wuye9036/CppTemplateTutorial] 关于 B(A::*)(C&) 语义的理解 (#46)


B(A::*)(C&)就是A的成员函数, 其类型是参数为C&, 返回B

―

**Comment by vczh** [comment]
@dongmingsun 不只是指定作用域，这个指针是不能被转成`B(*)(C&)`的。
