### ISSUE TITLE
2.1节SIMD指令函数的定义是否有错 ？

### ISSUE THREAD

**Issue by xylcbd** [wuye9036/CppTemplateTutorial#5]
Int8,16: N/A
Int32  : VInt32Mul(int32 * 4, int32 * 4)
Int64  : VInt64Mul(int64 * 2, int64 * 2)
Float  : VInt64Mul(float * 2, float * 2)

参数：int32 * 4, int32 * 4 ，2和4做参数是否有错误 ，还是有其他含义？

**Comment by wuye9036** [comment]
没有错，是伪代码。不过我会修正一下这里的代码形式。
