### ISSUE TITLE
为了便于讨论，建议开启Discussions板块功能

### ISSUE THREAD

**Issue by ichdream** [wuye9036/CppTemplateTutorial#64]
Github最近新增了一个功能，即Discussions板块，每一个resp都有，默认不开通。
这种文档性质的项目，感觉比较适合开通这个“讨论区”功能，详细的情况可以自己探索下试试。

**Comment by ichdream** [comment]
刚刚才注意到⚠️，好多年未更新了。。。

**Comment by wuye9036** [comment]
Discussion is enabled.
